# About this Notebook

It is first Jupyter Notebook for this data set.

I researched all variables in this Jupyter Notebook. 

For example, unique variables, min or max and so on.

# Data

This is a dataset containing records from the new crime incident report system, which includes a reduced set of fields focused on capturing the type of incident as well as when and where it occurred.

**Link:** https://www.kaggle.com/ankkur13/boston-crime-data

# 1. Import

In [1]:
import numpy as np
import pandas as pd

# 2. Read data

In [2]:
df = pd.read_csv('boston-crime-data/crime.csv', encoding='latin-1')

In [3]:
print(df.shape)
df.columns

(303371, 17)


Index(['INCIDENT_NUMBER', 'OFFENSE_CODE', 'OFFENSE_CODE_GROUP',
       'OFFENSE_DESCRIPTION', 'DISTRICT', 'REPORTING_AREA', 'SHOOTING',
       'OCCURRED_ON_DATE', 'YEAR', 'MONTH', 'DAY_OF_WEEK', 'HOUR', 'UCR_PART',
       'STREET', 'Lat', 'Long', 'Location'],
      dtype='object')

# 3. Functions

In [ ]:
#

# 4. Variable

##### INCIDENT_NUMBER

Maybe, it is not usefull

In [4]:
df['INCIDENT_NUMBER'][0:10]

0    I182054381
1    I182054379
2    I182054378
3    I182054376
4    I182054374
5    I182054372
6    I182054371
7    I182054369
8    I182054368
9    I182054366
Name: INCIDENT_NUMBER, dtype: object

##### OFFENSE_CODE

Offense code

In [5]:
df['OFFENSE_CODE'][0:10]

0    3301
1    3114
2     619
3     617
4    3410
5    3201
6    2647
7    3115
8    3115
9     613
Name: OFFENSE_CODE, dtype: int64

In [6]:
len(df['OFFENSE_CODE'].unique())

221

##### OFFENSE_CODE_GROUP

In [7]:
df['OFFENSE_CODE_GROUP'][0:10]

0         Verbal Disputes
1    Investigate Property
2                 Larceny
3                 Larceny
4                   Towed
5           Property Lost
6                   Other
7      Investigate Person
8      Investigate Person
9                 Larceny
Name: OFFENSE_CODE_GROUP, dtype: object

In [8]:
df['OFFENSE_CODE_GROUP'].describe()

count                              303371
unique                                 67
top       Motor Vehicle Accident Response
freq                                35342
Name: OFFENSE_CODE_GROUP, dtype: object

##### OFFENSE_DESCRIPTION

In [9]:
df['OFFENSE_DESCRIPTION'][0:10]

0                 VERBAL DISPUTE
1           INVESTIGATE PROPERTY
2             LARCENY ALL OTHERS
3    LARCENY THEFT FROM BUILDING
4            TOWED MOTOR VEHICLE
5                PROPERTY - LOST
6      THREATS TO DO BODILY HARM
7             INVESTIGATE PERSON
8             INVESTIGATE PERSON
9            LARCENY SHOPLIFTING
Name: OFFENSE_DESCRIPTION, dtype: object

In [10]:
df['OFFENSE_DESCRIPTION'].describe()

count                 303371
unique                   243
top       INVESTIGATE PERSON
freq                   17871
Name: OFFENSE_DESCRIPTION, dtype: object

##### DISTRICT

In [11]:
df['DISTRICT'][0:10]

0     B3
1    E18
2     B2
3     E5
4     C6
5     C6
6     B3
7    D14
8    E13
9    C11
Name: DISTRICT, dtype: object

In [12]:
df['DISTRICT'].unique()

array(['B3', 'E18', 'B2', 'E5', 'C6', 'D14', 'E13', 'C11', 'D4', 'A7',
       nan, 'A1', 'A15'], dtype=object)

##### REPORTING_AREA

In [13]:
df['REPORTING_AREA'][0:10]

0    428
1    481
2    182
3    714
4    211
5    186
6    427
7    788
8    571
9    450
Name: REPORTING_AREA, dtype: object

In [14]:
df['REPORTING_AREA'].describe()

count     303371
unique       879
top             
freq       19130
Name: REPORTING_AREA, dtype: object

##### SHOOTING

In [15]:
df['SHOOTING'][0:10]

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
Name: SHOOTING, dtype: object

In [16]:
df['SHOOTING'].unique()

array([nan, 'Y'], dtype=object)

##### OCCURRED_ON_DATE

In [17]:
df['OCCURRED_ON_DATE'][0:10]

0    2018-07-10 20:57:00
1    2018-07-10 21:16:00
2    2018-07-10 21:27:00
3    2018-07-10 18:39:00
4    2018-07-10 20:11:00
5    2018-07-10 21:08:00
6    2018-07-10 19:42:00
7    2018-07-10 20:17:00
8    2018-07-10 20:06:00
9    2018-07-10 20:28:00
Name: OCCURRED_ON_DATE, dtype: object

In [18]:
df['OCCURRED_ON_DATE'] = pd.to_datetime(df['OCCURRED_ON_DATE'])

In [19]:
df['OCCURRED_ON_DATE'].describe()

count                  303371
unique                 222011
top       2017-06-01 00:00:00
freq                       29
first     2015-06-15 00:00:00
last      2018-07-10 21:27:00
Name: OCCURRED_ON_DATE, dtype: object

##### YEAR

In [20]:
df['YEAR'].unique()

array([2018, 2017, 2015, 2016])

##### MONTH

In [21]:
print(len(df['MONTH'].unique()))
df['MONTH'].unique()

12


array([ 7,  6,  4,  5,  1,  8, 12,  2,  3,  9, 10, 11])

##### DAY_OF_WEEK

In [22]:
print(len(df['DAY_OF_WEEK'].unique()))
df['DAY_OF_WEEK'].unique()

7


array(['Tuesday', 'Saturday', 'Monday', 'Sunday', 'Thursday', 'Wednesday',
       'Friday'], dtype=object)

##### HOUR

In [23]:
print(len(df['HOUR'].unique()))
df['HOUR'].unique()

24


array([20, 21, 18, 19, 14,  7,  5, 17, 15, 10, 12, 16, 11,  0,  8, 13,  9,
       23,  2,  1,  6,  3,  4, 22])

##### UCR_PART

In [24]:
df['UCR_PART'][0:10]

0    Part Three
1    Part Three
2      Part One
3      Part One
4    Part Three
5    Part Three
6      Part Two
7    Part Three
8    Part Three
9      Part One
Name: UCR_PART, dtype: object

In [25]:
df['UCR_PART'].unique()

array(['Part Three', 'Part One', 'Part Two', 'Other', nan], dtype=object)

##### STREET

In [26]:
df['STREET'][0:10]

0    BLUE HILL AVE
1      ROCKDALE ST
2    BATCHELDER ST
3         VOGEL ST
4       W THIRD ST
5      ALLSTATE RD
6     FESSENDEN ST
7      CHISWICK RD
8    WASHINGTON ST
9    WASHINGTON ST
Name: STREET, dtype: object

In [27]:
df['STREET'].describe()

count            292753
unique             4595
top       WASHINGTON ST
freq              13504
Name: STREET, dtype: object

##### Lat

In [28]:
df['Lat'][0:10]

0    42.282829
1    42.266525
2    42.322496
3    42.262539
4    42.338964
5    42.326966
6    42.278560
7    42.339969
8    42.311906
9    42.291316
Name: Lat, dtype: float64

##### Long

In [29]:
df['Long'][0:10]

0   -71.091825
1   -71.098553
2   -71.069092
3   -71.165069
4   -71.048964
5   -71.061986
6   -71.091997
7   -71.150486
8   -71.102132
9   -71.071703
Name: Long, dtype: float64

##### Location

In [30]:
df['Location'][0:10]

0    (42.28282878, -71.09182490)
1    (42.26652466, -71.09855320)
2    (42.32249601, -71.06909180)
3    (42.26253888, -71.16506913)
4    (42.33896439, -71.04896420)
5    (42.32696647, -71.06198607)
6    (42.27855984, -71.09199697)
7    (42.33996911, -71.15048615)
8    (42.31190641, -71.10213227)
9    (42.29131613, -71.07170293)
Name: Location, dtype: object