# Import

In [161]:
import numpy as np
import pandas as pd

In [162]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [163]:
#from lightgbm import LGBMClassifier
#import xgboost as xgb

In [164]:
from sklearn.cross_validation import train_test_split

In [165]:
from sklearn.metrics import f1_score

# Functions

In [166]:
# DecisionTreeClassifier

def function_DecisionTreeClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    dec_tree = DecisionTreeClassifier()
    dec_tree = dec_tree.fit(X_train, Y_train)

    # predict
    dec_tree_pred = dec_tree.predict(X_test)
    
    # score
    dec_tree_score = f1_score(Y_test, dec_tree_pred, average=None)
    dec_tree_score_micro = f1_score(Y_test, dec_tree_pred, average='micro')
    
    return dec_tree_score, dec_tree_score_micro

In [167]:
# ExtraTreeClassifier

def function_ExtraTreeClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    ext_tree = ExtraTreeClassifier()
    ext_tree = ext_tree.fit(X_train, Y_train)

    # predict
    ext_tree_pred = ext_tree.predict(X_test)
    
    # score
    ext_tree_score = f1_score(Y_test, ext_tree_pred, average=None)
    ext_tree_score_micro = f1_score(Y_test, ext_tree_pred, average='micro')
    
    return ext_tree_score, ext_tree_score_micro

In [168]:
# RandomForestClassifier

def function_RandomForestClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    ran_for = RandomForestClassifier()
    ran_for = ran_for.fit(X_train, Y_train)

    # predict
    ran_for_pred = ran_for.predict(X_test)
    
    # score
    ran_for_score = f1_score(Y_test, ran_for_pred, average=None)
    ran_for_score_micro = f1_score(Y_test, ran_for_pred, average='micro')
    
    return ran_for_score, ran_for_score_micro

In [169]:
# LGBMClassifier
'''
def function_LGBMClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    lgbm = LGBMClassifier()
    lgbm = lgbm.fit(X_train, Y_train)

    # predict
    lgbm_pred = lgbm.predict(X_test)
    
    # score
    lgbm_score = f1_score(Y_test, lgbm_pred, average=None)
    lgbm_score_micro = f1_score(Y_test, lgbm_pred, average='micro')
    
    return lgbm_score, lgbm_score_micro
'''

"\ndef function_LGBMClassifier(X_train, Y_train, X_test, Y_test):\n    \n    # fit\n    lgbm = LGBMClassifier()\n    lgbm = lgbm.fit(X_train, Y_train)\n\n    # predict\n    lgbm_pred = lgbm.predict(X_test)\n    \n    # score\n    lgbm_score = f1_score(Y_test, lgbm_pred, average=None)\n    lgbm_score_micro = f1_score(Y_test, lgbm_pred, average='micro')\n    \n    return lgbm_score, lgbm_score_micro\n"

In [170]:
# BernoulliNB

def function_BernoulliNB(X_train, Y_train, X_test, Y_test):
    
    # fit
    bernoulli = BernoulliNB()
    bernoulli = bernoulli.fit(X_train, Y_train)

    # predict
    bernoulli_pred = bernoulli.predict(X_test)
    
    # score
    bernoulli_score = f1_score(Y_test, bernoulli_pred, average=None)
    bernoulli_score_micro = f1_score(Y_test, bernoulli_pred, average='micro')
    
    return bernoulli_score, bernoulli_score_micro

In [171]:
# KNeighborsClassifier

def function_KNeighborsClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    kn = KNeighborsClassifier()
    kn = kn.fit(X_train, Y_train)

    # predict
    kn_pred = kn.predict(X_test)
    
    # score
    kn_score = f1_score(Y_test, kn_pred, average=None)
    kn_score_micro = f1_score(Y_test, kn_pred, average='micro')
    
    return kn_score, kn_score_micro

In [172]:
# GaussianNB

def function_GaussianNB(X_train, Y_train, X_test, Y_test):
    
    # fit
    gaus = GaussianNB()
    gaus = gaus.fit(X_train, Y_train)

    # predict
    gaus_pred = gaus.predict(X_test)
    
    # score
    gaus_score = f1_score(Y_test, gaus_pred, average=None)
    gaus_score_micro = f1_score(Y_test, gaus_pred, average='micro')
    
    return gaus_score, gaus_score_micro

# Data

In [173]:
df = pd.read_csv('data.csv')

In [174]:
df = df.drop('Unnamed: 0',1)
df = df.drop('Unnamed: 0.1',1)
df = df.drop('Unnamed: 0.1.1',1)

In [175]:
df.columns

Index(['DAY_OF_WEEK', 'DISTRICT', 'HOUR', 'Lat', 'Long', 'MONTH',
       'OCCURRED_ON_DATE', 'OFFENSE_CODE_GROUP', 'REPORTING_AREA', 'SHOOTING',
       'UCR_PART', 'YEAR', 'Day', 'Night', 'ToNight', 'ToDay', 'DAY',
       'temperatureMin', 'temperatureMax', 'precipitation', 'snow',
       'temperatureDifference', 'clust_50', 'clust_100', 'clust_200',
       'Universities_colleges_distance_25',
       'Universities_colleges_distance_min',
       'Universities_colleges_number_near', 'Public_schools_distance_25',
       'Public_schools_distance_min', 'Public_schools_number_near',
       'Non-Public_schools_distance_25', 'Non-Public_schools_distance_min',
       'Non-Public_schools_number_near'],
      dtype='object')

In [176]:
df = df[[
    'DAY_OF_WEEK', 
    'DISTRICT', 
    'HOUR', 
    #'Lat', 
    #'Long', 
    'MONTH',
    'REPORTING_AREA', 
    'Day', 
    'Night', 
    'ToNight', 
    'ToDay', 
    'temperatureMin', 
    'temperatureMax', 
    'precipitation', 
    'snow',
    'temperatureDifference', 
    'clust_50', 
    'clust_100', 
    'clust_200',
    'Universities_colleges_distance_25',
    'Universities_colleges_distance_min',
    'Universities_colleges_number_near', 
    'Public_schools_distance_25',
    'Public_schools_distance_min', 
    'Public_schools_number_near',
    'Non-Public_schools_distance_25', 
    'Non-Public_schools_distance_min',
    'Non-Public_schools_number_near',
    'OFFENSE_CODE_GROUP'
]]

In [177]:
df.isnull().sum()

DAY_OF_WEEK                               0
DISTRICT                               1776
HOUR                                      0
MONTH                                     0
REPORTING_AREA                        20265
Day                                       0
Night                                     0
ToNight                                   0
ToDay                                     0
temperatureMin                            0
temperatureMax                            0
precipitation                         69889
snow                                  54332
temperatureDifference                     0
clust_50                                  0
clust_100                                 0
clust_200                                 0
Universities_colleges_distance_25     20020
Universities_colleges_distance_min    20020
Universities_colleges_number_near         0
Public_schools_distance_25            20020
Public_schools_distance_min           20020
Public_schools_number_near      

In [178]:
df['OFFENSE_CODE_GROUP'].value_counts().head(11)

Other                              94887
Motor Vehicle Accident Response    50952
Larceny                            50405
Medical Assistance                 40666
Simple Assault                     33528
Violations                         33449
Investigate Person                 31683
Vandalism                          28750
Drug Violation                     28637
Larceny From Motor Vehicle         23588
Towed                              18807
Name: OFFENSE_CODE_GROUP, dtype: int64

In [179]:
list_offense_code_group = (
    'Motor Vehicle Accident Response',
    'Larceny',
    'Medical Assistance',
    'Simple Assault',
    'Violations',
    'Investigate Person',
    'Vandalism',
    'Drug Violation',
    'Larceny From Motor Vehicle',
    'Towed'
)

In [180]:
df_model = pd.DataFrame()

In [181]:
i = 0

while i < len(list_offense_code_group):

    df_model= df_model.append(df.loc[df['OFFENSE_CODE_GROUP'] == list_offense_code_group[i]])
    
    i+=1

In [182]:
df.shape

(575226, 27)

In [183]:
df_model.shape

(340465, 27)

In [184]:
df_model.columns

Index(['DAY_OF_WEEK', 'DISTRICT', 'HOUR', 'MONTH', 'REPORTING_AREA', 'Day',
       'Night', 'ToNight', 'ToDay', 'temperatureMin', 'temperatureMax',
       'precipitation', 'snow', 'temperatureDifference', 'clust_50',
       'clust_100', 'clust_200', 'Universities_colleges_distance_25',
       'Universities_colleges_distance_min',
       'Universities_colleges_number_near', 'Public_schools_distance_25',
       'Public_schools_distance_min', 'Public_schools_number_near',
       'Non-Public_schools_distance_25', 'Non-Public_schools_distance_min',
       'Non-Public_schools_number_near', 'OFFENSE_CODE_GROUP'],
      dtype='object')

In [185]:
# DAY_OF_WEEK

df_model['DAY_OF_WEEK'] = df_model['DAY_OF_WEEK'].map({
    'Tuesday':2, 
    'Saturday':6, 
    'Monday':1, 
    'Sunday':7, 
    'Thursday':4, 
    'Wednesday':3,
    'Friday':5
})

df_model['DAY_OF_WEEK'].unique()

array([7, 1, 2, 3, 4, 5, 6])

In [186]:
df_model.fillna(0, inplace = True)

In [187]:
df_model.isnull().sum()

DAY_OF_WEEK                           0
DISTRICT                              0
HOUR                                  0
MONTH                                 0
REPORTING_AREA                        0
Day                                   0
Night                                 0
ToNight                               0
ToDay                                 0
temperatureMin                        0
temperatureMax                        0
precipitation                         0
snow                                  0
temperatureDifference                 0
clust_50                              0
clust_100                             0
clust_200                             0
Universities_colleges_distance_25     0
Universities_colleges_distance_min    0
Universities_colleges_number_near     0
Public_schools_distance_25            0
Public_schools_distance_min           0
Public_schools_number_near            0
Non-Public_schools_distance_25        0
Non-Public_schools_distance_min       0


In [188]:
y = df_model['OFFENSE_CODE_GROUP']

In [189]:
y.unique()

array(['Motor Vehicle Accident Response', 'Larceny', 'Medical Assistance',
       'Simple Assault', 'Violations', 'Investigate Person', 'Vandalism',
       'Drug Violation', 'Larceny From Motor Vehicle', 'Towed'],
      dtype=object)

In [190]:
y = y.map({
    'Motor Vehicle Accident Response':1, 
    'Larceny':2, 
    'Medical Assistance':3,
    'Simple Assault':4, 
    'Violations':5, 
    'Investigate Person':6, 
    'Vandalism':7,
    'Drug Violation':8, 
    'Larceny From Motor Vehicle':9, 
    'Towed':10
})

In [191]:
x = df_model.drop('OFFENSE_CODE_GROUP', 1)

In [192]:
x.columns

Index(['DAY_OF_WEEK', 'DISTRICT', 'HOUR', 'MONTH', 'REPORTING_AREA', 'Day',
       'Night', 'ToNight', 'ToDay', 'temperatureMin', 'temperatureMax',
       'precipitation', 'snow', 'temperatureDifference', 'clust_50',
       'clust_100', 'clust_200', 'Universities_colleges_distance_25',
       'Universities_colleges_distance_min',
       'Universities_colleges_number_near', 'Public_schools_distance_25',
       'Public_schools_distance_min', 'Public_schools_number_near',
       'Non-Public_schools_distance_25', 'Non-Public_schools_distance_min',
       'Non-Public_schools_number_near'],
      dtype='object')

# Split data

In [193]:
# Split dataframe into random train and test subsets

X_train, X_test, Y_train, Y_test = train_test_split(
    x,
    y, 
    test_size = 0.1,
    random_state=42
)

print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(306418, 26) (306418,)
(34047, 26) (34047,)


# Modeling

In [194]:
function_DecisionTreeClassifier(X_train, Y_train, X_test, Y_test)

(array([0.25671642, 0.3511709 , 0.18015343, 0.14659074, 0.18971631,
        0.12366534, 0.12825375, 0.46232352, 0.15953307, 0.25529633]),
 0.231679736834376)

In [195]:
function_ExtraTreeClassifier(X_train, Y_train, X_test, Y_test)

(array([0.25524786, 0.34895628, 0.18340504, 0.15102224, 0.18468401,
        0.13101134, 0.13310225, 0.44557477, 0.14462541, 0.25202812]),
 0.23047551913531295)

In [196]:
# 0.28701

function_RandomForestClassifier(X_train, Y_train, X_test, Y_test)

(array([0.33182719, 0.41671092, 0.22818328, 0.1861928 , 0.23015996,
        0.13276311, 0.1273134 , 0.52730627, 0.18052257, 0.3213279 ]),
 0.28563456398507947)

In [197]:
# function_LGBMClassifier(X_train, Y_train, X_test, Y_test)

In [198]:
function_BernoulliNB(X_train, Y_train, X_test, Y_test)

/home/oleksandr/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([0.18866375, 0.27593835, 0.        , 0.        , 0.04799165,
        0.        , 0.18090901, 0.00344234, 0.        , 0.        ]),
 0.16641701177783652)

In [199]:
function_KNeighborsClassifier(X_train, Y_train, X_test, Y_test)

(array([0.34439926, 0.42627615, 0.24726503, 0.16363333, 0.20951751,
        0.12988002, 0.12304988, 0.42475284, 0.17348609, 0.27645377]),
 0.28152260111023)

In [200]:
function_GaussianNB(X_train, Y_train, X_test, Y_test)

/home/oleksandr/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([0.199282  , 0.26847987, 0.        , 0.        , 0.08982322,
        0.        , 0.        , 0.        , 0.        , 0.        ]),
 0.16259876053690486)