# 1. Import

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from lightgbm import LGBMClassifier

from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [3]:
from sklearn.cross_validation import train_test_split

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [4]:
from sklearn.metrics import f1_score

# 2. Functions

In [5]:
# DecisionTreeClassifier

def function_DecisionTreeClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    dec_tree = DecisionTreeClassifier()
    dec_tree = dec_tree.fit(X_train, Y_train)

    # predict
    dec_tree_pred = dec_tree.predict(X_test)
    
    # score
    dec_tree_score = f1_score(Y_test, dec_tree_pred, average=None)
    dec_tree_score_micro = f1_score(Y_test, dec_tree_pred, average='micro')
    
    return dec_tree_score, dec_tree_score_micro

In [6]:
# ExtraTreeClassifier

def function_ExtraTreeClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    ext_tree = ExtraTreeClassifier()
    ext_tree = ext_tree.fit(X_train, Y_train)

    # predict
    ext_tree_pred = ext_tree.predict(X_test)
    
    # score
    ext_tree_score = f1_score(Y_test, ext_tree_pred, average=None)
    ext_tree_score_micro = f1_score(Y_test, ext_tree_pred, average='micro')
    
    return ext_tree_score, ext_tree_score_micro

In [7]:
# RandomForestClassifier

def function_RandomForestClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    ran_for = RandomForestClassifier()
    ran_for = ran_for.fit(X_train, Y_train)

    # predict
    ran_for_pred = ran_for.predict(X_test)
    
    # score
    ran_for_score = f1_score(Y_test, ran_for_pred, average=None)
    ran_for_score_micro = f1_score(Y_test, ran_for_pred, average='micro')
    
    return ran_for_score, ran_for_score_micro

In [8]:
# LGBMClassifier

def function_LGBMClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    lgbm = LGBMClassifier()
    lgbm = lgbm.fit(X_train, Y_train)

    # predict
    lgbm_pred = lgbm.predict(X_test)
    
    # score
    lgbm_score = f1_score(Y_test, lgbm_pred, average=None)
    lgbm_score_micro = f1_score(Y_test, lgbm_pred, average='micro')
    
    return lgbm_score, lgbm_score_micro

In [9]:
# BernoulliNB

def function_BernoulliNB(X_train, Y_train, X_test, Y_test):
    
    # fit
    bernoulli = BernoulliNB()
    bernoulli = bernoulli.fit(X_train, Y_train)

    # predict
    bernoulli_pred = bernoulli.predict(X_test)
    
    # score
    bernoulli_score = f1_score(Y_test, bernoulli_pred, average=None)
    bernoulli_score_micro = f1_score(Y_test, bernoulli_pred, average='micro')
    
    return bernoulli_score, bernoulli_score_micro

In [10]:
# KNeighborsClassifier

def function_KNeighborsClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    kn = KNeighborsClassifier()
    kn = kn.fit(X_train, Y_train)

    # predict
    kn_pred = kn.predict(X_test)
    
    # score
    kn_score = f1_score(Y_test, kn_pred, average=None)
    kn_score_micro = f1_score(Y_test, kn_pred, average='micro')
    
    return kn_score, kn_score_micro

In [11]:
# GaussianNB

def function_GaussianNB(X_train, Y_train, X_test, Y_test):
    
    # fit
    gaus = GaussianNB()
    gaus = gaus.fit(X_train, Y_train)

    # predict
    gaus_pred = gaus.predict(X_test)
    
    # score
    gaus_score = f1_score(Y_test, gaus_pred, average=None)
    gaus_score_micro = f1_score(Y_test, gaus_pred, average='micro')
    
    return gaus_score, gaus_score_micro

# 3. Data

In [12]:
df = pd.read_csv('finish-crime-weather.csv')

In [13]:
df.head(10)

Unnamed: 0  Unnamed: 0.1 DAY_OF_WEEK  DISTRICT  HOUR        Lat       Long  \
0           0             0      Sunday       2.0     6  42.346381 -71.103794   
1           1             1      Sunday       1.0     6  42.316841 -71.074585   
2           2             2      Sunday       2.0     6  42.342841 -71.096990   
3           3             3      Sunday       1.0     6  42.316441 -71.065829   
4           4             4      Sunday       9.0     7  42.270516 -71.119900   
5           5             5      Sunday       3.0     7  42.313282 -71.053005   
6           6             6      Sunday       1.0     7  42.324251 -71.086209   
7           7             7      Sunday       4.0     7  42.349246 -71.063784   
8           8             8      Sunday       7.0     7  42.351746 -71.165909   
9           9             9      Sunday       9.0     8  42.259383 -71.117294   

   MONTH     OCCURRED_ON_DATE    OFFENSE_CODE_GROUP          ...            \
0      7  2012-07-08 06:00:00  Residential Burglary          ...             
1      7  2012-07-08 06:03:00    Aggravated Assault          ...             
2      7  2012-07-08 06:26:00               Robbery          ...             
3      7  2012-07-08 06:56:00                 Other          ...             
4      7  2012-07-08 07:15:00               Robbery          ...             
5      7  2012-07-08 07:32:00               Robbery          ...             
6      7  2012-07-08 07:50:00               Robbery          ...             
7      7  2012-07-08 07:50:00        Simple Assault          ...             
8      7  2012-07-08 07:53:00    Medical Assistance          ...             
9      7  2012-07-08 08:05:00    Medical Assistance          ...             

   Day  Night  ToNight  ToDay  DAY  temperatureMin  temperatureMax  \
0    1      0       16      0    8            30.0            45.0   
1    1      0       16      0    8            30.0            45.0   
2    1      0       16      0    8            30.0            45.0   
3    1      0       16      0    8            30.0            45.0   
4    1      0       15      0    8            30.0            45.0   
5    1      0       15      0    8            30.0            45.0   
6    1      0       15      0    8            30.0            45.0   
7    1      0       15      0    8            30.0            45.0   
8    1      0       15      0    8            30.0            45.0   
9    1      0       14      0    8            30.0            45.0   

   precipitation  snow  temperatureDifference  
0            0.0   0.0                   15.0  
1            0.0   0.0                   15.0  
2            0.0   0.0                   15.0  
3            0.0   0.0                   15.0  
4            0.0   0.0                   15.0  
5            0.0   0.0                   15.0  
6            0.0   0.0                   15.0  
7            0.0   0.0                   15.0  
8            0.0   0.0                   15.0  
9            0.0   0.0                   15.0  

[10 rows x 24 columns]

In [200]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'DAY_OF_WEEK', 'DISTRICT', 'HOUR', 'Lat',
       'Long', 'MONTH', 'OCCURRED_ON_DATE', 'OFFENSE_CODE_GROUP',
       'REPORTING_AREA', 'SHOOTING', 'UCR_PART', 'YEAR', 'Day', 'Night',
       'ToNight', 'ToDay', 'DAY', 'temperatureMin', 'temperatureMax',
       'precipitation', 'snow', 'temperatureDifference'],
      dtype='object')

In [201]:
df = df[[
    'DAY_OF_WEEK', 
    'DISTRICT', 
    'HOUR', 
    'Lat', 
    'Long', 
    'MONTH',
    'REPORTING_AREA',
    'temperatureMin', 
    'temperatureMax',
    'precipitation', 
    'snow',
    'Day',
    'Night',
    'ToNight',
    'ToDay',
    'temperatureDifference',
    'OFFENSE_CODE_GROUP'
]]

In [202]:
df.head()

DAY_OF_WEEK  DISTRICT  HOUR        Lat       Long  MONTH  REPORTING_AREA  \
0      Sunday       2.0     6  42.346381 -71.103794      7           629.0   
1      Sunday       1.0     6  42.316841 -71.074585      7           327.0   
2      Sunday       2.0     6  42.342841 -71.096990      7           625.0   
3      Sunday       1.0     6  42.316441 -71.065829      7           258.0   
4      Sunday       9.0     7  42.270516 -71.119900      7           496.0   

   temperatureMin  temperatureMax  precipitation  snow  Day  Night  ToNight  \
0            30.0            45.0            0.0   0.0    1      0       16   
1            30.0            45.0            0.0   0.0    1      0       16   
2            30.0            45.0            0.0   0.0    1      0       16   
3            30.0            45.0            0.0   0.0    1      0       16   
4            30.0            45.0            0.0   0.0    1      0       15   

   ToDay  temperatureDifference    OFFENSE_CODE_GROUP  
0      0                   15.0  Residential Burglary  
1      0                   15.0    Aggravated Assault  
2      0                   15.0               Robbery  
3      0                   15.0                 Other  
4      0                   15.0               Robbery

In [203]:
df['OFFENSE_CODE_GROUP'].value_counts().head(11)

Other                              94887
Motor Vehicle Accident Response    50952
Larceny                            50405
Medical Assistance                 40666
Simple Assault                     33528
Violations                         33449
Investigate Person                 31683
Vandalism                          28750
Drug Violation                     28637
Larceny From Motor Vehicle         23588
Towed                              18807
Name: OFFENSE_CODE_GROUP, dtype: int64

In [204]:
list_offense_code_group = (
    'Motor Vehicle Accident Response',
    'Larceny',
    'Medical Assistance',
    'Simple Assault',
    'Violations',
    'Investigate Person',
    'Vandalism',
    'Drug Violation',
    'Larceny From Motor Vehicle',
    'Towed'
)

In [205]:
df_model = pd.DataFrame()

In [206]:
i = 0

while i < len(list_offense_code_group):

    df_model= df_model.append(df.loc[df['OFFENSE_CODE_GROUP'] == list_offense_code_group[i]])
    
    i+=1

In [207]:
df.shape

(575226, 17)

In [208]:
df_model.shape

(340465, 17)

In [209]:
df_model.head()

DAY_OF_WEEK  DISTRICT  HOUR        Lat       Long  MONTH  REPORTING_AREA  \
47       Sunday      10.0    12  42.379551 -71.038219      7            24.0   
90       Sunday       8.0    16  42.302651 -71.114525      7           651.0   
95       Sunday       2.0    16  42.337301 -71.078059      7           170.0   
121      Sunday       8.0    18  42.324741 -71.104244      7           906.0   
185      Monday       3.0     0  42.300661 -71.072050      7           344.0   

     temperatureMin  temperatureMax  precipitation  snow  Day  Night  ToNight  \
47             30.0            45.0            0.0   0.0    1      0       10   
90             30.0            45.0            0.0   0.0    1      0        6   
95             30.0            45.0            0.0   0.0    1      0        6   
121            30.0            45.0            0.0   0.0    1      0        4   
185            25.0            39.9            0.0   0.0    0      1        0   

     ToDay  temperatureDifference               OFFENSE_CODE_GROUP  
47       0                   15.0  Motor Vehicle Accident Response  
90       0                   15.0  Motor Vehicle Accident Response  
95       0                   15.0  Motor Vehicle Accident Response  
121      0                   15.0  Motor Vehicle Accident Response  
185      6                   14.9  Motor Vehicle Accident Response

In [210]:
# DAY_OF_WEEK

df_model['DAY_OF_WEEK'] = df_model['DAY_OF_WEEK'].map({
    'Tuesday':2, 
    'Saturday':6, 
    'Monday':1, 
    'Sunday':7, 
    'Thursday':4, 
    'Wednesday':3,
    'Friday':5
})

df_model['DAY_OF_WEEK'].unique()

array([7, 1, 2, 3, 4, 5, 6])

In [211]:
df_model.fillna(0, inplace = True)

In [212]:
y = df_model['OFFENSE_CODE_GROUP']

In [213]:
y.shape

(340465,)

In [214]:
y.unique()

array(['Motor Vehicle Accident Response', 'Larceny', 'Medical Assistance',
       'Simple Assault', 'Violations', 'Investigate Person', 'Vandalism',
       'Drug Violation', 'Larceny From Motor Vehicle', 'Towed'], dtype=object)

In [215]:
y = y.map({
    'Motor Vehicle Accident Response':1, 
    'Larceny':2, 
    'Medical Assistance':3,
    'Simple Assault':4, 
    'Violations':5, 
    'Investigate Person':6, 
    'Vandalism':7,
    'Drug Violation':8, 
    'Larceny From Motor Vehicle':9, 
    'Towed':10
})

In [216]:
x = df_model.drop('OFFENSE_CODE_GROUP', 1)

In [217]:
x.columns

Index(['DAY_OF_WEEK', 'DISTRICT', 'HOUR', 'Lat', 'Long', 'MONTH',
       'REPORTING_AREA', 'temperatureMin', 'temperatureMax', 'precipitation',
       'snow', 'Day', 'Night', 'ToNight', 'ToDay', 'temperatureDifference'],
      dtype='object')

# Split data

In [218]:
# Split dataframe into random train and test subsets

X_train, X_test, Y_train, Y_test = train_test_split(
    x,
    y, 
    test_size = 0.1,
    random_state=42
)

print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(306418, 16) (306418,)
(34047, 16) (34047,)


# Modeling

In [219]:
function_DecisionTreeClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.24617524,  0.343722  ,  0.19047619,  0.15167962,  0.17310849,
         0.12943633,  0.11786877,  0.4516129 ,  0.14840085,  0.24356869]),
 0.22645166975063882)

In [220]:
function_ExtraTreeClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.21309371,  0.26605596,  0.16796344,  0.1272242 ,  0.15047962,
         0.12307198,  0.12275862,  0.38402406,  0.11172472,  0.19215156]),
 0.19185243927511969)

In [221]:
function_RandomForestClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.28417238,  0.37912275,  0.19006788,  0.15470992,  0.18969668,
         0.11831843,  0.11996679,  0.50475658,  0.15009381,  0.27728426]),
 0.25341439774429464)

In [222]:
function_LGBMClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.3209848 ,  0.42315207,  0.20277852,  0.140681  ,  0.24449464,
         0.06496644,  0.07879429,  0.40830062,  0.15135492,  0.34475077]),
 0.27976033130672306)

In [223]:
function_BernoulliNB(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.16100703,  0.27415162,  0.        ,  0.        ,  0.031639  ,
         0.        ,  0.18091345,  0.00139762,  0.        ,  0.        ]),
 0.16251064704672952)

In [224]:
function_KNeighborsClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.25196308,  0.30487605,  0.15180361,  0.1132755 ,  0.13946386,
         0.09483794,  0.10860335,  0.28772309,  0.09295528,  0.21038436]),
 0.1996651687373337)

In [225]:
function_GaussianNB(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.18537252,  0.28065083,  0.06155703,  0.        ,  0.00059049,
         0.02069781,  0.1793116 ,  0.00473293,  0.01899486,  0.09533267]),
 0.16735688900637355)