# 1. Import

In [ ]:
import numpy as np
import pandas as pd

In [134]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from lightgbm import LGBMClassifier

from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [135]:
from sklearn.cross_validation import train_test_split

In [136]:
from sklearn.metrics import f1_score

# 2. Functions

In [137]:
# DecisionTreeClassifier

def function_DecisionTreeClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    dec_tree = DecisionTreeClassifier()
    dec_tree = dec_tree.fit(X_train, Y_train)

    # predict
    dec_tree_pred = dec_tree.predict(X_test)
    
    # score
    dec_tree_score = f1_score(Y_test, dec_tree_pred, average=None)
    dec_tree_score_micro = f1_score(Y_test, dec_tree_pred, average='micro')
    
    return dec_tree_score, dec_tree_score_micro

In [138]:
# ExtraTreeClassifier

def function_ExtraTreeClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    ext_tree = ExtraTreeClassifier()
    ext_tree = ext_tree.fit(X_train, Y_train)

    # predict
    ext_tree_pred = ext_tree.predict(X_test)
    
    # score
    ext_tree_score = f1_score(Y_test, ext_tree_pred, average=None)
    ext_tree_score_micro = f1_score(Y_test, ext_tree_pred, average='micro')
    
    return ext_tree_score, ext_tree_score_micro

In [139]:
# RandomForestClassifier

def function_RandomForestClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    ran_for = RandomForestClassifier()
    ran_for = ran_for.fit(X_train, Y_train)

    # predict
    ran_for_pred = ran_for.predict(X_test)
    
    # score
    ran_for_score = f1_score(Y_test, ran_for_pred, average=None)
    ran_for_score_micro = f1_score(Y_test, ran_for_pred, average='micro')
    
    return ran_for_score, ran_for_score_micro

In [140]:
# LGBMClassifier

def function_LGBMClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    lgbm = LGBMClassifier()
    lgbm = lgbm.fit(X_train, Y_train)

    # predict
    lgbm_pred = lgbm.predict(X_test)
    
    # score
    lgbm_score = f1_score(Y_test, lgbm_pred, average=None)
    lgbm_score_micro = f1_score(Y_test, lgbm_pred, average='micro')
    
    return lgbm_score, lgbm_score_micro

In [141]:
# BernoulliNB

def function_BernoulliNB(X_train, Y_train, X_test, Y_test):
    
    # fit
    bernoulli = BernoulliNB()
    bernoulli = bernoulli.fit(X_train, Y_train)

    # predict
    bernoulli_pred = bernoulli.predict(X_test)
    
    # score
    bernoulli_score = f1_score(Y_test, bernoulli_pred, average=None)
    bernoulli_score_micro = f1_score(Y_test, bernoulli_pred, average='micro')
    
    return bernoulli_score, bernoulli_score_micro

In [142]:
# KNeighborsClassifier

def function_KNeighborsClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    kn = KNeighborsClassifier()
    kn = kn.fit(X_train, Y_train)

    # predict
    kn_pred = kn.predict(X_test)
    
    # score
    kn_score = f1_score(Y_test, kn_pred, average=None)
    kn_score_micro = f1_score(Y_test, kn_pred, average='micro')
    
    return kn_score, kn_score_micro

In [143]:
# GaussianNB

def function_GaussianNB(X_train, Y_train, X_test, Y_test):
    
    # fit
    gaus = GaussianNB()
    gaus = gaus.fit(X_train, Y_train)

    # predict
    gaus_pred = gaus.predict(X_test)
    
    # score
    gaus_score = f1_score(Y_test, gaus_pred, average=None)
    gaus_score_micro = f1_score(Y_test, gaus_pred, average='micro')
    
    return gaus_score, gaus_score_micro

# 3. Data

In [144]:
df = pd.read_csv('crimes.csv')

In [145]:
df.columns

Index(['Unnamed: 0', 'DAY_OF_WEEK', 'DISTRICT', 'HOUR', 'Lat', 'Long', 'MONTH',
       'OCCURRED_ON_DATE', 'OFFENSE_CODE_GROUP', 'REPORTING_AREA', 'SHOOTING',
       'UCR_PART', 'YEAR', 'Day', 'Night', 'ToNight', 'ToDay', 'DayNumber',
       'precipitation', 'temperature', 'dewpoint', 'humidity', 'wind'],
      dtype='object')

In [146]:
df = df.drop('Unnamed: 0',1)

In [147]:
df = df[[
    'DAY_OF_WEEK',
    'DISTRICT',
    'HOUR',
    'Lat', 
    'Long', 
    'MONTH',
    'OFFENSE_CODE_GROUP', 
    'REPORTING_AREA',
    'UCR_PART',
    'Day', 
    'Night',
    'ToNight', 
    'ToDay',
    'precipitation', 
    'temperature', 
    'dewpoint', 
    'humidity', 
    'wind'
]]

In [148]:
df.head()

DAY_OF_WEEK  DISTRICT  HOUR        Lat       Long  MONTH  \
0      Sunday       2.0     6  42.346381 -71.103794      7   
1      Sunday       1.0     6  42.316841 -71.074585      7   
2      Sunday       2.0     6  42.342841 -71.096990      7   
3      Sunday       1.0     6  42.316441 -71.065829      7   
4      Sunday       9.0     7  42.270516 -71.119900      7   

     OFFENSE_CODE_GROUP  REPORTING_AREA  UCR_PART  Day  Night  ToNight  ToDay  \
0  Residential Burglary           629.0       1.0    1      0       16      0   
1    Aggravated Assault           327.0       1.0    1      0       16      0   
2               Robbery           625.0       1.0    1      0       16      0   
3                 Other           258.0       1.0    1      0       16      0   
4               Robbery           496.0       1.0    1      0       15      0   

   precipitation  temperature  dewpoint  humidity  wind  
0            0.0         80.0      59.0      51.0   9.0  
1            0.0         80.0      59.0      51.0   9.0  
2            0.0         80.0      59.0      51.0   9.0  
3            0.0         80.0      59.0      51.0   9.0  
4            0.0         80.0      59.0      51.0   9.0

In [149]:
# DAY_OF_WEEK

df['DAY_OF_WEEK'] = df['DAY_OF_WEEK'].map({
    'Tuesday':2, 
    'Saturday':6, 
    'Monday':1, 
    'Sunday':7, 
    'Thursday':4, 
    'Wednesday':3,
    'Friday':5
})

df['DAY_OF_WEEK'].unique()

array([7, 1, 2, 3, 5, 4, 6])

In [150]:
df.isnull().sum()

DAY_OF_WEEK             0
DISTRICT               97
HOUR                    0
Lat                   736
Long                  736
MONTH                   0
OFFENSE_CODE_GROUP      0
REPORTING_AREA        592
UCR_PART                0
Day                     0
Night                   0
ToNight                 0
ToDay                   0
precipitation           0
temperature             0
dewpoint                0
humidity                0
wind                    0
dtype: int64

In [151]:
df.fillna(0, inplace = True)

In [152]:
df.OFFENSE_CODE_GROUP.unique()

array(['Residential Burglary', 'Aggravated Assault', 'Robbery', 'Other',
       'Simple Assault', 'Medical Assistance', 'Violations', 'Fraud',
       'Property Found', 'Investigate Person', 'Towed',
       'Investigate Property', 'Drug Violation', 'Missing Person Located',
       'Property Lost', 'Larceny', 'Auto Theft', 'Warrant Arrests',
       'Vandalism', 'Motor Vehicle Accident Response',
       'Larceny From Motor Vehicle', 'Verbal Disputes'], dtype=object)

In [153]:
df.OFFENSE_CODE_GROUP.value_counts()

Other                              41210
Violations                         27888
Larceny                            26485
Simple Assault                     18744
Medical Assistance                 18236
Motor Vehicle Accident Response    16022
Vandalism                          14378
Investigate Person                 13824
Larceny From Motor Vehicle         13570
Drug Violation                     13291
Property Lost                       9157
Fraud                               9153
Towed                               8065
Residential Burglary                7345
Investigate Property                7062
Aggravated Assault                  6257
Robbery                             5315
Missing Person Located              5051
Auto Theft                          5027
Property Found                      4579
Verbal Disputes                     3419
Warrant Arrests                     2477
Name: OFFENSE_CODE_GROUP, dtype: int64

In [154]:
list_offense_code_group = (
    'Other',
    'Motor Vehicle Accident Response',
    'Larceny',
    'Medical Assistance',
    'Simple Assault',
    'Violations',
    'Investigate Person',
    'Vandalism',
    'Drug Violation',
    'Larceny From Motor Vehicle'
)

In [155]:
df.shape

(276555, 18)

In [156]:
df_model_1 = pd.DataFrame()

In [157]:
i = 0

while i < len(list_offense_code_group):

    df_model_1 = df_model_1.append(df.loc[df['OFFENSE_CODE_GROUP'] == list_offense_code_group[i]])
    
    i+=1

In [158]:
df_model_1.shape

(203648, 18)

In [159]:
df_model_1.head()

DAY_OF_WEEK  DISTRICT  HOUR        Lat       Long  MONTH  \
3             7       1.0     6  42.316441 -71.065829      7   
10            7       2.0     8  42.341806 -71.097080      7   
18            7       1.0     9  42.321701 -71.081909      7   
24            7       7.0    10  42.351681 -71.125190      7   
48            7       6.0    12  42.325436 -71.063873      7   

   OFFENSE_CODE_GROUP  REPORTING_AREA  UCR_PART  Day  Night  ToNight  ToDay  \
3               Other           258.0       1.0    1      0       16      0   
10              Other           626.0       1.0    1      0       14      0   
18              Other           296.0       2.0    1      0       13      0   
24              Other           796.0       2.0    1      0       12      0   
48              Other             0.0       2.0    1      0       10      0   

    precipitation  temperature  dewpoint  humidity  wind  
3             0.0         80.0      59.0      51.0   9.0  
10            0.0         80.0      59.0      51.0   9.0  
18            0.0         80.0      59.0      51.0   9.0  
24            0.0         80.0      59.0      51.0   9.0  
48            0.0         80.0      59.0      51.0   9.0

In [160]:
x = df_model_1[[
    'DAY_OF_WEEK',
    'DISTRICT',
    'HOUR',
    'Lat', 
    'Long', 
    'MONTH',
    'REPORTING_AREA',
    'UCR_PART',
    'Day', 
    'Night',
    'ToNight', 
    'ToDay',
    'precipitation', 
    'temperature', 
    'dewpoint', 
    'humidity', 
    'wind'
]]

In [161]:
y = df_model_1['OFFENSE_CODE_GROUP']

In [162]:
y = y.map({
    'Other':1, 
    'Motor Vehicle Accident Response':2, 
    'Larceny':3,
    'Medical Assistance':4, 
    'Simple Assault':5, 
    'Violations':6,
    'Investigate Person':7, 
    'Vandalism':8, 
    'Drug Violation':9,
    'Larceny From Motor Vehicle':10
})

# Split data

In [163]:
# Split dataframe into random train and test subsets

X_train, X_test, Y_train, Y_test = train_test_split(
    x,
    y, 
    test_size = 0.1,
    random_state=42
)

print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(183283, 17) (183283,)
(20365, 17) (20365,)


# Modeling

X - > 'DAY_OF_WEEK',
    'DISTRICT',
    'HOUR',
    'Lat', 
    'Long', 
    'MONTH',
    'REPORTING_AREA',
    'UCR_PART',
    'Day', 
    'Night',
    'ToNight', 
    'ToDay',
    'precipitation', 
    'temperature', 
    'dewpoint', 
    'humidity', 
    'wind'

Y - > OFFENSE_CODE_GROUP

In [164]:
function_DecisionTreeClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.32452469,  0.61620603,  0.70528109,  0.35758601,  0.26426108,
         0.38367038,  0.30468204,  0.22505878,  0.42205882,  0.47239488]),
 0.40947704394794993)

In [165]:
function_ExtraTreeClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.30934479,  0.57886485,  0.66058186,  0.36424209,  0.23182067,
         0.3714443 ,  0.27480371,  0.22344828,  0.33074935,  0.40316206]),
 0.38134053523201572)

In [166]:
function_RandomForestClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.36471664,  0.6519685 ,  0.74854998,  0.4       ,  0.27490145,
         0.44676198,  0.23929471,  0.2045929 ,  0.48392702,  0.44462948]),
 0.44384974220476309)

In [167]:
function_LGBMClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.34092804,  0.70890086,  0.77555778,  0.48334036,  0.24071429,
         0.52557361,  0.20435685,  0.15279241,  0.50508625,  0.49241147]),
 0.48386938374662414)

In [168]:
function_BernoulliNB(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.03670546,  0.        ,  0.2408377 ,  0.        ,  0.        ,
         0.10170423,  0.        ,  0.16808448,  0.00149925,  0.        ]),
 0.13842376626565187)

In [169]:
function_KNeighborsClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.31957916,  0.14020897,  0.31222707,  0.12825397,  0.11884984,
         0.19077042,  0.06150692,  0.07796759,  0.22382365,  0.13762811]),
 0.21831573778541616)

In [170]:
function_GaussianNB(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.02566412,  0.59593023,  0.70849991,  0.10521236,  0.        ,
         0.22589099,  0.39576399,  0.28471703,  0.28792658,  0.38095238]),
 0.33459366560274983)