# 1. Import

In [ ]:
import numpy as np
import pandas as pd

In [39]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from lightgbm import LGBMClassifier

from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [40]:
from sklearn.cross_validation import train_test_split

In [41]:
from sklearn.metrics import f1_score

# 2. Functions

In [42]:
# DecisionTreeClassifier

def function_DecisionTreeClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    dec_tree = DecisionTreeClassifier()
    dec_tree = dec_tree.fit(X_train, Y_train)

    # predict
    dec_tree_pred = dec_tree.predict(X_test)
    
    # score
    dec_tree_score = f1_score(Y_test, dec_tree_pred, average=None)
    dec_tree_score_micro = f1_score(Y_test, dec_tree_pred, average='micro')
    
    return dec_tree_score, dec_tree_score_micro

In [43]:
# ExtraTreeClassifier

def function_ExtraTreeClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    ext_tree = ExtraTreeClassifier()
    ext_tree = ext_tree.fit(X_train, Y_train)

    # predict
    ext_tree_pred = ext_tree.predict(X_test)
    
    # score
    ext_tree_score = f1_score(Y_test, ext_tree_pred, average=None)
    ext_tree_score_micro = f1_score(Y_test, ext_tree_pred, average='micro')
    
    return ext_tree_score, ext_tree_score_micro

In [44]:
# RandomForestClassifier

def function_RandomForestClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    ran_for = RandomForestClassifier()
    ran_for = ran_for.fit(X_train, Y_train)

    # predict
    ran_for_pred = ran_for.predict(X_test)
    
    # score
    ran_for_score = f1_score(Y_test, ran_for_pred, average=None)
    ran_for_score_micro = f1_score(Y_test, ran_for_pred, average='micro')
    
    return ran_for_score, ran_for_score_micro

In [45]:
# LGBMClassifier

def function_LGBMClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    lgbm = LGBMClassifier()
    lgbm = lgbm.fit(X_train, Y_train)

    # predict
    lgbm_pred = lgbm.predict(X_test)
    
    # score
    lgbm_score = f1_score(Y_test, lgbm_pred, average=None)
    lgbm_score_micro = f1_score(Y_test, lgbm_pred, average='micro')
    
    return lgbm_score, lgbm_score_micro

In [46]:
# BernoulliNB

def function_BernoulliNB(X_train, Y_train, X_test, Y_test):
    
    # fit
    bernoulli = BernoulliNB()
    bernoulli = bernoulli.fit(X_train, Y_train)

    # predict
    bernoulli_pred = bernoulli.predict(X_test)
    
    # score
    bernoulli_score = f1_score(Y_test, bernoulli_pred, average=None)
    bernoulli_score_micro = f1_score(Y_test, bernoulli_pred, average='micro')
    
    return bernoulli_score, bernoulli_score_micro

In [47]:
# KNeighborsClassifier

def function_KNeighborsClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    kn = KNeighborsClassifier()
    kn = kn.fit(X_train, Y_train)

    # predict
    kn_pred = kn.predict(X_test)
    
    # score
    kn_score = f1_score(Y_test, kn_pred, average=None)
    kn_score_micro = f1_score(Y_test, kn_pred, average='micro')
    
    return kn_score, kn_score_micro

In [48]:
# GaussianNB

def function_GaussianNB(X_train, Y_train, X_test, Y_test):
    
    # fit
    gaus = GaussianNB()
    gaus = gaus.fit(X_train, Y_train)

    # predict
    gaus_pred = gaus.predict(X_test)
    
    # score
    gaus_score = f1_score(Y_test, gaus_pred, average=None)
    gaus_score_micro = f1_score(Y_test, gaus_pred, average='micro')
    
    return gaus_score, gaus_score_micro

# 3. Data

In [49]:
df = pd.read_csv('crimes.csv')

In [50]:
df.columns

Index(['Unnamed: 0', 'DAY_OF_WEEK', 'DISTRICT', 'HOUR', 'Lat', 'Long', 'MONTH',
       'OCCURRED_ON_DATE', 'OFFENSE_CODE_GROUP', 'REPORTING_AREA', 'SHOOTING',
       'UCR_PART', 'YEAR', 'Day', 'Night', 'ToNight', 'ToDay', 'DayNumber',
       'precipitation', 'temperature', 'dewpoint', 'humidity', 'wind'],
      dtype='object')

In [51]:
df = df.drop('Unnamed: 0',1)

In [52]:
df = df[[
    'DAY_OF_WEEK', 
    'DISTRICT', 
    'HOUR', 
    'MONTH',
    'UCR_PART', 
    'Day', 
    'Night', 
    'ToNight', 
    'ToDay', 
    'precipitation', 
    'temperature', 
    'dewpoint', 
    'humidity', 
    'wind'
]]

In [53]:
df.head()

DAY_OF_WEEK  DISTRICT  HOUR  MONTH  UCR_PART  Day  Night  ToNight  ToDay  \
0      Sunday       2.0     6      7       1.0    1      0       16      0   
1      Sunday       1.0     6      7       1.0    1      0       16      0   
2      Sunday       2.0     6      7       1.0    1      0       16      0   
3      Sunday       1.0     6      7       1.0    1      0       16      0   
4      Sunday       9.0     7      7       1.0    1      0       15      0   

   precipitation  temperature  dewpoint  humidity  wind  
0            0.0         80.0      59.0      51.0   9.0  
1            0.0         80.0      59.0      51.0   9.0  
2            0.0         80.0      59.0      51.0   9.0  
3            0.0         80.0      59.0      51.0   9.0  
4            0.0         80.0      59.0      51.0   9.0

In [54]:
# DAY_OF_WEEK

df['DAY_OF_WEEK'] = df['DAY_OF_WEEK'].map({
    'Tuesday':2, 
    'Saturday':6, 
    'Monday':1, 
    'Sunday':7, 
    'Thursday':4, 
    'Wednesday':3,
    'Friday':5
})

df['DAY_OF_WEEK'].unique()

array([7, 1, 2, 3, 5, 4, 6])

In [55]:
df.isnull().sum()

DAY_OF_WEEK       0
DISTRICT         97
HOUR              0
MONTH             0
UCR_PART          0
Day               0
Night             0
ToNight           0
ToDay             0
precipitation     0
temperature       0
dewpoint          0
humidity          0
wind              0
dtype: int64

In [56]:
df = df.dropna()

In [57]:
x = df[[
    'DAY_OF_WEEK', 
    'HOUR', 
    'MONTH',
    'UCR_PART', 
    'Day', 
    'Night', 
    'ToNight', 
    'ToDay', 
    'precipitation', 
    'temperature', 
    'dewpoint', 
    'humidity', 
    'wind'
]]

In [58]:
y = df['DISTRICT']

# 4. Split

In [59]:
# Split dataframe into random train and test subsets

X_train, X_test, Y_train, Y_test = train_test_split(
    x,
    y, 
    test_size = 0.1,
    random_state=42
)

print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(248812, 13) (248812,)
(27646, 13) (27646,)


# 5. Modeling

X - > 'DAY_OF_WEEK', 
    'HOUR', 
    'MONTH',
    'UCR_PART', 
    'Day', 
    'Night', 
    'ToNight', 
    'ToDay', 
    'precipitation', 
    'temperature', 
    'dewpoint', 
    'humidity', 
    'wind'
    
Y - > DISTRICT

In [60]:
function_DecisionTreeClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.22770304,  0.1929642 ,  0.15310881,  0.13556428,  0.10650633,
         0.07923655,  0.06845053,  0.05328893,  0.0546875 ,  0.04099723,
         0.05070755,  0.01273885]), 0.14417998987195255)

In [61]:
function_ExtraTreeClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.22504328,  0.19293873,  0.1526638 ,  0.13513977,  0.10391276,
         0.08060307,  0.06546135,  0.04769874,  0.05728395,  0.04129464,
         0.04798128,  0.01552393]), 0.14323952832236128)

In [62]:
function_RandomForestClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.19941216,  0.17110358,  0.15781651,  0.14445707,  0.11446369,
         0.09226263,  0.09040683,  0.06481791,  0.07457627,  0.06440958,
         0.06255507,  0.02255639]), 0.13159227374665414)

In [63]:
function_LGBMClassifier(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.25658999,  0.2723742 ,  0.11509533,  0.1088171 ,  0.02188982,
         0.01740724,  0.00762995,  0.00120555,  0.0027027 ,  0.        ,
         0.00477707,  0.        ]), 0.17463647543948491)

In [64]:
function_BernoulliNB(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.24677732,  0.        ,  0.        ,  0.1806623 ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]), 0.14280546914562686)

In [65]:
function_KNeighborsClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.22659881,  0.18083984,  0.14751698,  0.13121769,  0.09707844,
         0.06573341,  0.0638578 ,  0.03952569,  0.0450676 ,  0.03057758,
         0.0450237 ,  0.01897019]), 0.14081603125226072)

In [66]:
function_GaussianNB(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.24917321,  0.2423767 ,  0.04670913,  0.16442861,  0.00382409,
         0.01583113,  0.00096712,  0.        ,  0.        ,  0.        ,
         0.00315706,  0.        ]), 0.16222961730449251)