# 1. Import

In [268]:
import numpy as np
import pandas as pd

In [269]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from lightgbm import LGBMClassifier

from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [270]:
from sklearn.cross_validation import train_test_split

In [271]:
from sklearn.metrics import f1_score

# 2. Function

In [272]:
# DecisionTreeClassifier

def function_DecisionTreeClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    dec_tree = DecisionTreeClassifier()
    dec_tree = dec_tree.fit(X_train, Y_train)

    # predict
    dec_tree_pred = dec_tree.predict(X_test)
    
    # score
    dec_tree_score = f1_score(Y_test, dec_tree_pred, average=None)
    dec_tree_score_micro = f1_score(Y_test, dec_tree_pred, average='micro')
    
    return dec_tree_score, dec_tree_score_micro

In [273]:
# ExtraTreeClassifier

def function_ExtraTreeClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    ext_tree = ExtraTreeClassifier()
    ext_tree = ext_tree.fit(X_train, Y_train)

    # predict
    ext_tree_pred = ext_tree.predict(X_test)
    
    # score
    ext_tree_score = f1_score(Y_test, ext_tree_pred, average=None)
    ext_tree_score_micro = f1_score(Y_test, ext_tree_pred, average='micro')
    
    return ext_tree_score, ext_tree_score_micro

In [274]:
# RandomForestClassifier

def function_RandomForestClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    ran_for = RandomForestClassifier()
    ran_for = ran_for.fit(X_train, Y_train)

    # predict
    ran_for_pred = ran_for.predict(X_test)
    
    # score
    ran_for_score = f1_score(Y_test, ran_for_pred, average=None)
    ran_for_score_micro = f1_score(Y_test, ran_for_pred, average='micro')
    
    return ran_for_score, ran_for_score_micro

In [275]:
# LGBMClassifier

def function_LGBMClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    lgbm = LGBMClassifier()
    lgbm = lgbm.fit(X_train, Y_train)

    # predict
    lgbm_pred = lgbm.predict(X_test)
    
    # score
    lgbm_score = f1_score(Y_test, lgbm_pred, average=None)
    lgbm_score_micro = f1_score(Y_test, lgbm_pred, average='micro')
    
    return lgbm_score, lgbm_score_micro

In [276]:
# BernoulliNB

def function_BernoulliNB(X_train, Y_train, X_test, Y_test):
    
    # fit
    bernoulli = BernoulliNB()
    bernoulli = bernoulli.fit(X_train, Y_train)

    # predict
    bernoulli_pred = bernoulli.predict(X_test)
    
    # score
    bernoulli_score = f1_score(Y_test, bernoulli_pred, average=None)
    bernoulli_score_micro = f1_score(Y_test, bernoulli_pred, average='micro')
    
    return bernoulli_score, bernoulli_score_micro

In [277]:
# KNeighborsClassifier

def function_KNeighborsClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    kn = KNeighborsClassifier()
    kn = kn.fit(X_train, Y_train)

    # predict
    kn_pred = kn.predict(X_test)
    
    # score
    kn_score = f1_score(Y_test, kn_pred, average=None)
    kn_score_micro = f1_score(Y_test, kn_pred, average='micro')
    
    return kn_score, kn_score_micro

In [278]:
# GaussianNB

def function_GaussianNB(X_train, Y_train, X_test, Y_test):
    
    # fit
    gaus = GaussianNB()
    gaus = gaus.fit(X_train, Y_train)

    # predict
    gaus_pred = gaus.predict(X_test)
    
    # score
    gaus_score = f1_score(Y_test, gaus_pred, average=None)
    gaus_score_micro = f1_score(Y_test, gaus_pred, average='micro')
    
    return gaus_score, gaus_score_micro

# Preparation data

In [279]:
df = pd.read_csv('crime-boston_1.csv')

In [280]:
df.shape

(575226, 18)

In [281]:
df.head()

Unnamed: 0  Unnamed: 0.1 DAY_OF_WEEK  DISTRICT  HOUR        Lat       Long  \
0           0             0      Sunday       2.0     6  42.346381 -71.103794   
1           1             1      Sunday       1.0     6  42.316841 -71.074585   
2           2             2      Sunday       2.0     6  42.342841 -71.096990   
3           3             3      Sunday       1.0     6  42.316441 -71.065829   
4           4             4      Sunday       9.0     7  42.270516 -71.119900   

   MONTH     OCCURRED_ON_DATE    OFFENSE_CODE_GROUP  REPORTING_AREA  SHOOTING  \
0      7  2012-07-08 06:00:00  Residential Burglary           629.0       0.0   
1      7  2012-07-08 06:03:00    Aggravated Assault           327.0       1.0   
2      7  2012-07-08 06:26:00               Robbery           625.0       0.0   
3      7  2012-07-08 06:56:00                 Other           258.0       0.0   
4      7  2012-07-08 07:15:00               Robbery           496.0       0.0   

   UCR_PART  YEAR  Day  Night  ToNight  ToDay  
0       1.0  2012    1      0       16      0  
1       1.0  2012    1      0       16      0  
2       1.0  2012    1      0       16      0  
3       1.0  2012    1      0       16      0  
4       1.0  2012    1      0       15      0

In [282]:
df = df.drop('Unnamed: 0',1)
df = df.drop('Unnamed: 0.1',1)

# 3. For modeling

###### Multi classification

Y - OFFENSE_CODE_GROUP

X - 'DISTRICT','REPORTING_AREA','MONTH','DAY_OF_WEEK', 'HOUR','Lat','Long', 'OFFENSE_CODE_GROUP',

'Day','Night', 'ToDay', 'ToNight'

In [283]:
df['OFFENSE_CODE_GROUP'].value_counts().head(10)

Other                              94887
Motor Vehicle Accident Response    50952
Larceny                            50405
Medical Assistance                 40666
Simple Assault                     33528
Violations                         33449
Investigate Person                 31683
Vandalism                          28750
Drug Violation                     28637
Larceny From Motor Vehicle         23588
Name: OFFENSE_CODE_GROUP, dtype: int64

In [284]:
list_offense_code_group = (
    'Other',
    'Motor Vehicle Accident Response',
    'Larceny',
    'Medical Assistance',
    'Simple Assault',
    'Violations',
    'Investigate Person',
    'Vandalism',
    'Drug Violation',
    'Larceny From Motor Vehicle'
)

In [285]:
df_model_1 = pd.DataFrame()

In [286]:
i = 0

while i < len(list_offense_code_group):

    df_model_1 = df_model_1.append(df.loc[df['OFFENSE_CODE_GROUP'] == list_offense_code_group[i]])
    
    i+=1

In [287]:
list_column = ['DISTRICT','REPORTING_AREA','MONTH','DAY_OF_WEEK',
               'HOUR','Lat','Long', 'OFFENSE_CODE_GROUP','Day','Night','ToDay','ToNight']

In [288]:
df_model_1 = df_model_1[list_column]

In [289]:
# DAY_OF_WEEK

df_model_1['DAY_OF_WEEK'] = df_model_1['DAY_OF_WEEK'].map({
    'Tuesday':2, 
    'Saturday':6, 
    'Monday':1, 
    'Sunday':7, 
    'Thursday':4, 
    'Wednesday':3,
    'Friday':5
})

df_model_1['DAY_OF_WEEK'].unique()

array([7, 1, 2, 3, 4, 5, 6])

In [290]:
df_model_1.fillna(0, inplace = True)

In [291]:
x = df_model_1[['DISTRICT','REPORTING_AREA','MONTH','DAY_OF_WEEK',
               'HOUR','Lat','Long']]

In [292]:
y = df_model_1['OFFENSE_CODE_GROUP']

In [293]:
y.unique()

array(['Other', 'Motor Vehicle Accident Response', 'Larceny',
       'Medical Assistance', 'Simple Assault', 'Violations',
       'Investigate Person', 'Vandalism', 'Drug Violation',
       'Larceny From Motor Vehicle'], dtype=object)

In [294]:
y = y.map({
    'Other':1, 
    'Motor Vehicle Accident Response':2, 
    'Larceny':3,
    'Medical Assistance':4, 
    'Simple Assault':5, 
    'Violations':6,
    'Investigate Person':7, 
    'Vandalism':8, 
    'Drug Violation':9,
    'Larceny From Motor Vehicle':10
})

# 4. Split data

In [295]:
# Split dataframe into random train and test subsets

X_train, X_test, Y_train, Y_test = train_test_split(
    x,
    y, 
    test_size = 0.1,
    random_state=42
)

print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(374890, 7) (374890,)
(41655, 7) (41655,)


# 5. Modeling. Multi classification

In [296]:
function_DecisionTreeClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.30737057,  0.23610144,  0.29669221,  0.16924209,  0.11370218,
         0.156     ,  0.11434837,  0.10806054,  0.41072332,  0.14374171]),
 0.22700756211739287)

In [297]:
function_ExtraTreeClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.30401946,  0.21232877,  0.26823152,  0.14472879,  0.10787879,
         0.13855235,  0.10168394,  0.10089841,  0.39477212,  0.13327469]),
 0.21293962309446646)

In [298]:
function_RandomForestClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.35149032,  0.24899522,  0.33664911,  0.1658318 ,  0.1102791 ,
         0.16435107,  0.10111496,  0.09071819,  0.46775058,  0.15478723]),
 0.25802424678910096)

In [299]:
function_LGBMClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.38285018,  0.2478185 ,  0.36319356,  0.0482852 ,  0.04825884,
         0.16852081,  0.02217431,  0.01242236,  0.36248637,  0.13347686]),
 0.28628015844436444)

In [300]:
function_BernoulliNB(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.37169162,  0.19590336,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ]),
 0.23452166606649863)

In [301]:
function_KNeighborsClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.34640357,  0.21964659,  0.27526029,  0.12050618,  0.08846454,
         0.12335464,  0.07527334,  0.07790368,  0.33683435,  0.12337466]),
 0.23418557196014886)

In [302]:
function_GaussianNB(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.34441981,  0.18752483,  0.25480427,  0.01144689,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ]),
 0.21759692713959908)