# 1. Import

In [88]:
import numpy as np
import pandas as pd

In [89]:
from sklearn.cross_validation import train_test_split

In [90]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from lightgbm import LGBMClassifier

from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [91]:
from sklearn.metrics import f1_score

# 2. Functions

In [93]:
# DecisionTreeClassifier

def function_DecisionTreeClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    dec_tree = DecisionTreeClassifier()
    dec_tree = dec_tree.fit(X_train, Y_train)

    # predict
    dec_tree_pred = dec_tree.predict(X_test)
    
    # score
    dec_tree_score = f1_score(Y_test, dec_tree_pred, average=None)
    dec_tree_score_micro = f1_score(Y_test, dec_tree_pred, average='micro')
    
    return dec_tree_score, dec_tree_score_micro

In [94]:
# ExtraTreeClassifier

def function_ExtraTreeClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    ext_tree = ExtraTreeClassifier()
    ext_tree = ext_tree.fit(X_train, Y_train)

    # predict
    ext_tree_pred = ext_tree.predict(X_test)
    
    # score
    ext_tree_score = f1_score(Y_test, ext_tree_pred, average=None)
    ext_tree_score_micro = f1_score(Y_test, ext_tree_pred, average='micro')
    
    return ext_tree_score, ext_tree_score_micro

In [95]:
# RandomForestClassifier

def function_RandomForestClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    ran_for = RandomForestClassifier()
    ran_for = ran_for.fit(X_train, Y_train)

    # predict
    ran_for_pred = ran_for.predict(X_test)
    
    # score
    ran_for_score = f1_score(Y_test, ran_for_pred, average=None)
    ran_for_score_micro = f1_score(Y_test, ran_for_pred, average='micro')
    
    return ran_for_score, ran_for_score_micro

In [96]:
# LGBMClassifier

def function_LGBMClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    lgbm = LGBMClassifier()
    lgbm = lgbm.fit(X_train, Y_train)

    # predict
    lgbm_pred = lgbm.predict(X_test)
    
    # score
    lgbm_score = f1_score(Y_test, lgbm_pred, average=None)
    lgbm_score_micro = f1_score(Y_test, lgbm_pred, average='micro')
    
    return lgbm_score, lgbm_score_micro

In [97]:
# BernoulliNB

def function_BernoulliNB(X_train, Y_train, X_test, Y_test):
    
    # fit
    bernoulli = BernoulliNB()
    bernoulli = bernoulli.fit(X_train, Y_train)

    # predict
    bernoulli_pred = bernoulli.predict(X_test)
    
    # score
    bernoulli_score = f1_score(Y_test, bernoulli_pred, average=None)
    bernoulli_score_micro = f1_score(Y_test, bernoulli_pred, average='micro')
    
    return bernoulli_score, bernoulli_score_micro

In [98]:
# KNeighborsClassifier

def function_KNeighborsClassifier(X_train, Y_train, X_test, Y_test):
    
    # fit
    kn = KNeighborsClassifier()
    kn = kn.fit(X_train, Y_train)

    # predict
    kn_pred = kn.predict(X_test)
    
    # score
    kn_score = f1_score(Y_test, kn_pred, average=None)
    kn_score_micro = f1_score(Y_test, kn_pred, average='micro')
    
    return kn_score, kn_score_micro

In [99]:
# GaussianNB

def function_GaussianNB(X_train, Y_train, X_test, Y_test):
    
    # fit
    gaus = GaussianNB()
    gaus = gaus.fit(X_train, Y_train)

    # predict
    gaus_pred = gaus.predict(X_test)
    
    # score
    gaus_score = f1_score(Y_test, gaus_pred, average=None)
    gaus_score_micro = f1_score(Y_test, gaus_pred, average='micro')
    
    return gaus_score, gaus_score_micro

# 3. Data

In [ ]:
df = pd.read_csv('crime-boston_1.csv')

In [100]:
df.shape

(575226, 18)

In [101]:
df.head()

Unnamed: 0  Unnamed: 0.1 DAY_OF_WEEK  DISTRICT  HOUR        Lat       Long  \
0           0             0      Sunday       2.0     6  42.346381 -71.103794   
1           1             1      Sunday       1.0     6  42.316841 -71.074585   
2           2             2      Sunday       2.0     6  42.342841 -71.096990   
3           3             3      Sunday       1.0     6  42.316441 -71.065829   
4           4             4      Sunday       9.0     7  42.270516 -71.119900   

   MONTH     OCCURRED_ON_DATE    OFFENSE_CODE_GROUP  REPORTING_AREA  SHOOTING  \
0      7  2012-07-08 06:00:00  Residential Burglary           629.0       0.0   
1      7  2012-07-08 06:03:00    Aggravated Assault           327.0       1.0   
2      7  2012-07-08 06:26:00               Robbery           625.0       0.0   
3      7  2012-07-08 06:56:00                 Other           258.0       0.0   
4      7  2012-07-08 07:15:00               Robbery           496.0       0.0   

   UCR_PART  YEAR  Day  Night  ToNight  ToDay  
0       1.0  2012    1      0       16      0  
1       1.0  2012    1      0       16      0  
2       1.0  2012    1      0       16      0  
3       1.0  2012    1      0       16      0  
4       1.0  2012    1      0       15      0

In [102]:
df = df.drop('Unnamed: 0',1)
df = df.drop('Unnamed: 0.1',1)

In [103]:
df_model = df[[
    'DISTRICT',
    'MONTH',
    'DAY_OF_WEEK',
    'HOUR',
    'Day',
    'Night',
    'ToDay',
    'ToNight'
]]

In [104]:
# DAY_OF_WEEK

df_model['DAY_OF_WEEK'] = df_model['DAY_OF_WEEK'].map({
    'Tuesday':2, 
    'Saturday':6, 
    'Monday':1, 
    'Sunday':7, 
    'Thursday':4, 
    'Wednesday':3,
    'Friday':5
})

df_model['DAY_OF_WEEK'].unique()

/home/olexandr/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.


array([7, 1, 2, 3, 5, 4, 6])

In [105]:
df_model.isnull().sum()

DISTRICT       1776
MONTH             0
DAY_OF_WEEK       0
HOUR              0
Day               0
Night             0
ToDay             0
ToNight           0
dtype: int64

In [106]:
df_model = df_model.dropna()

In [107]:
x = df_model[['MONTH','DAY_OF_WEEK','HOUR','Day','Night','ToNight','ToDay']]
y = df_model['DISTRICT']

# 4. Split data

In [108]:
# Split dataframe into random train and test subsets

X_train, X_test, Y_train, Y_test = train_test_split(
    x,
    y, 
    test_size = 0.1,
    random_state=42
)

print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(516105, 7) (516105,)
(57345, 7) (57345,)


# 5. Modeling

X - > 'MONTH','DAY_OF_WEEK','HOUR','Day','Night','ToNight','ToDay'

Y - > DISTRICT

In [109]:
function_DecisionTreeClassifier(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.2503023 ,  0.1830873 ,  0.15094584,  0.13332001,  0.04193458,
         0.01379013,  0.00646445,  0.        ,  0.00194363,  0.        ,
         0.        ,  0.        ]), 0.15588107071235505)

In [110]:
function_ExtraTreeClassifier(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.2503023 ,  0.1830873 ,  0.15094584,  0.13332001,  0.04193458,
         0.01379013,  0.00646445,  0.        ,  0.00194363,  0.        ,
         0.        ,  0.        ]), 0.15588107071235505)

In [111]:
function_RandomForestClassifier(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.24683894,  0.17967975,  0.15541075,  0.13474291,  0.04281675,
         0.01537148,  0.00599101,  0.        ,  0.002589  ,  0.        ,
         0.        ,  0.        ]), 0.15319557066875927)

In [112]:
function_LGBMClassifier(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.26384967,  0.17146049,  0.06647491,  0.11861978,  0.0016787 ,
         0.01049639,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]), 0.16024064870520532)

In [113]:
function_BernoulliNB(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.25153507,  0.        ,  0.        ,  0.17724179,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]), 0.1449123724823437)

In [114]:
function_KNeighborsClassifier(X_train, Y_train, X_test, Y_test)

(array([ 0.21742146,  0.17396707,  0.14100842,  0.10867052,  0.08764136,
         0.04994571,  0.04388715,  0.03737916,  0.03218506,  0.02506879,
         0.02820282,  0.01011378]), 0.13164181707210743)

In [115]:
function_GaussianNB(X_train, Y_train, X_test, Y_test)

/home/olexandr/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.22556391,  0.23010781,  0.        ,  0.16192373,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]), 0.15200976545470399)